[[professions]]
name = 'guardian'
specializations = ['Zeal', 'Radiance', 'Valor', 'Honor', 'Virtues', 'Dragonhunter', 'Firebrand', 'Willbender']
[professions.skills]
heal = ['Receive the Light', 'Litany of Wrath', 'Shelter', 'Signet of Resolve', 'Purification', 'Mantra of Solace', 'Reversal of Fortune']
utility = ['Hallowed Ground', 'Purging Flames', 'Sanctuary', 'Wall of Reflection', 'Contemplation of Purity', 'Judges Intervention', 'Merciful Intervention', 'Smite Condition', 'Hold The Line!', 'Advance!', 'Save Yourselves!', 'Stand Your Ground', 'Bane Signet', 'Signet of Judgment', 'Signet of Mercy', 'Signet of Wrath', 'Bow of Truth', 'Hammer of Wisdom', 'Shield of the Avenger', 'Sword of Justice', 'Fragments of Faith', 'Lights Judgment', 'Test of Faith', 'Procession of Blades', 'Mantra of Flame', 'Mantra of Lore', 'Matra of Truth', 'Mantra of Potence', 'Flash Combo', 'Heel Crack', 'Roiling Light', 'Whirling Light']
elite = ['Feel my Wrath!', 'Renewed Focus', 'Signet of Courage', 'Dragons Maw', 'Mantra of Liberation', 'Heavens Palm']
[professions.weapons]
[professions.weapons.base]
main_hand = ['mace', 'sword', 'scepter']
off_hand = ['focus', 'shield', 'torch']
two_hand = ['greatsword', 'hammer', 'staff']
[professions.weapons.heart_of_thorns]
two_hand = ['longbow']
[professions.weapons.path_of_fire]
main_hand = ['axe']
[professions.weapons.end_of_dragons]
off_hand = ['sword']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['pistol']
off_hand = ['pistol']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'revenant'
specializations = ['Corruption', 'Retribution', 'Salvation', 'Invocation', 'Devastation', 'Herald', 'Renegade', 'Vindicator']
[professions.skills]
heal = []
utility = []
elite = []
special = ['Assassin', 'Centaur', 'Demon', 'Dwarf', 'Dragon', 'Renegade', 'Alliance']
[professions.weapons]
[professions.weapons.base]
main_hand = ['mace', 'sword']
off_hand = ['axe', 'sword']
two_hand = ['hammer', 'staff']
[professions.weapons.heart_of_thorns]
off_hand = ['shield']
[professions.weapons.path_of_fire]
two_hand = ['shortbow']
[professions.weapons.end_of_dragons]
two_hand = ['greatsword']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['scepter']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'warrior'
specializations = ['Strength', 'Arms', 'Defence', 'Tactics', 'Discipline', 'Spellbreaker', 'Berserker', 'Bladesworn']
[professions.skills]
heal = ['Mending', 'To the Limit!', 'Healing Signet', 'Defiant Stance', 'Natural Healing', 'Blood Reckoning', 'Combat Stimulant']
utility = ['Banner of Defence', 'Banner of Dicipline', 'Banner of Strenght', 'Banner of Tactics', 'Bulls Charge', 'Kick', 'Stomp', 'Throw Bolas', 'Fear me!', 'For Great Justice!', 'On My Mark!', 'Shake It Off!', 'Dolyak Signet', 'Signet of Fury', 'Signet of Might', 'Signet of Stamina', 'Balanced Stance', 'Berserker Stance', 'Endure Pain', 'Frenzy', 'Sight Beyond Sight', 'Featherfoot Grace', 'Imminent Threat', 'Break Enchantments', 'Outrage', 'Shattering Blow', 'Sundering Leap', 'Wild Blow', 'Dragonspike Mine', 'Electric Fence', 'Flow Stabilizer', 'Overcharged Cartridges']
elite = ['Battle Standard', 'Rampage', 'Signet of Rage', 'Winds of Disenchantment', 'Head Butt', 'Tactical Reload']
[professions.weapons]
[professions.weapons.base]
main_hand = ['axe', 'mace', 'sword']
off_hand = ['axe', 'mace', 'sword', 'shield', 'warhorn']
two_hand = ['greatsword', 'hammer', 'longbow', 'rifle']
[professions.weapons.heart_of_thorns]
off_hand = ['torch']
[professions.weapons.path_of_fire]
main_hand = ['dagger']
off_hand = ['dagger']
[professions.weapons.end_of_dragons]
off_hand = ['pistol']
[professions.weapons.secrets_of_the_obscure]
two_hand = ['staff']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'ranger'
specializations = ['Marksmanship', 'Skirmishing', 'Wilderness Survival', 'Nature Magic', 'Beastmastery', 'Druid', 'Soulbeast', 'Untamed']
[professions.skills]
heal = ['We Heal as one!', 'Water Spirit', 'Troll Unguent', 'Healing Spring', 'Glyph of Rejuvenation', 'Bear Stance', 'Perilous Gift']
utility = ['Guard!', 'Protect Me!', 'Search and Rescue!', "Sic'em", 'Signet of Renewal', 'Signet of Stone', 'Signet of the Hunt', 'Signet of the Wild', 'Frost Spirit', 'Stone Spirit', 'Storm Spirit', 'Sun Spirit', 'Lightning Reflexes', 'Muddy Terrain', 'Quickening Zephyr', 'Sharpening Stone', 'Flame Trap', 'Frost Trap', 'Spike Trap', 'Vipers Nest', 'Glyph of Alignment', 'Glyph of Equality', 'Glyph of Unity', 'Glyph of the Tides', 'Dolyak Stance', 'Griffon Stance', 'Moa Stance', 'Vulture Stance', 'Exploding Spores', 'Mutate Conditions', 'Natures Binding', 'Unnatural Traversal']
elite = ['Strength of the Pack!', 'Spirit of Nature', 'Entangle', 'Glyph of the Stars', 'One Wolf Pack', 'Forests Fortification']
special = ['Arctodus', 'Black Bear', 'Brown Bear', 'Murrelow', 'Polar bear', 'Eagle', 'Hawk', 'Owl', 'Raven', 'White Raven', 'Alpine Wolf', 'Fern hound', 'Hyena', 'Krytan Drakehound', 'Wolf', 'Carrion Devourer', 'Lashtail Devourer', 'Whiptail Devourer', 'Ice Drake', 'Marsh Drake', 'Reef Drake', 'River Drake', 'Salamander Drake', 'Cheetah', 'Jaguar', 'Jungle Stalker', 'Lynx', 'Sand Lion', 'Snow Leopard', 'Tiger', 'Black Moa', 'Blue Moa', 'Pink Moa', 'Red Moa', 'White Moa', 'Boar', 'Pig', 'Siamoth', 'Warthog', 'Black Widow Spider', 'Cave Spider', 'Forest Spider', 'Jungle Spider', 'Electric Wyvern', 'Fire Wyvern', 'Armor Fish', 'Bristleback', 'Fanged Iboga', 'Jacaranda', 'Rock Gazelle', 'Smoke Scale', 'Phoenix', 'White Tiger', 'Wallow', 'Siege Turtle']
[professions.weapons]
[professions.weapons.base]
main_hand = ['axe', 'sword']
off_hand = ['axe', 'dagger', 'torch', 'warhorn']
two_hand = ['greatsword', 'longbow', 'shortbow']
[professions.weapons.heart_of_thorns]
two_hand = ['staff']
[professions.weapons.path_of_fire]
main_hand = ['dagger']
[professions.weapons.end_of_dragons]
two_hand = ['hammer']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['mace']
off_hand = ['mace']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'thief'
specializations = ['Deadly Arts', 'Critical Strikes', 'Shadow Arts', 'Acrobatics', 'Trickery', 'Daredevil', 'Deadeye', 'Specter']
[professions.skills]
heal = ['Hide in Shadows', 'Signet of Malice', 'Withdraw', 'Skelk Venom', 'Channeled Vigor', 'Malicious Restoration', 'Well of Gloom']
utility = ['Blinding Powder', 'Shadow Refuge', 'Shadowstep', 'Smoke Screen', 'Prepare Pitfall', 'Prepare Thousand Needles', 'Prepare Shadow Portal', 'Prepare Seal Area', 'Assassins Signet', 'Infiltrators Signet', 'Signet of Agility', 'Signet of Shadows', 'Caltrops', 'Haste', 'Roll for Initiative', 'Scorpion Wire', 'Devourer Venom', 'Ice Drake Venom', 'Skale Venom', 'Spider Venom', 'Bandits Defense', 'Distracting Daggers', 'Fist Furry', 'Impairing Daggers', 'Binding Shadow', 'Mercy', 'Shadow Flare', 'Shadow Gust', 'Well of Bounty', 'Well of Silence', 'Well of Sorrow', 'Well of Tears']
elite = ['Thieves Guild', 'Basilisk Venom', 'Dagger Storm', 'Impact Strike', 'Shadow Meld', 'Shadowfall']
[professions.weapons]
[professions.weapons.base]
main_hand = ['dagger', 'pistol', 'sword']
off_hand = ['dagger', 'pistol']
two_hand = ['shortbow']
[professions.weapons.heart_of_thorns]
two_hand = ['staff']
[professions.weapons.path_of_fire]
two_hand = ['rifle']
[professions.weapons.end_of_dragons]
main_hand = ['scepter']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['axe']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'engineer'
specializations = ['Explosives', 'Firearms', 'Inventions', 'Alchemy', 'Tools', 'Scrapper', 'Holosmith', 'Mechanist']
[professions.skills]
heal = ['A.E.D.', 'Elixer H', 'Healing Turret', 'Medkit', 'Medic Gyro', 'Coolant Blast', 'Rectifier Signet']
utility = ['Bomb kit', 'Grenade Kit', 'Elixir Gun', 'Flamethrower', 'Tool Kit', 'Elixir B', 'Elixir C', 'Elixir R', 'Elixir S', 'Elixir U', 'Personal Battering Ram', 'Rocket Boots', 'Slick Shoes', 'Throw Mine', 'Utility Goggles', 'Flame Turret', 'Net Turret', 'Rifle Turret', 'Harpoon Turret', 'Rocket Turret', 'Thumper Turret', 'Blast Gyro', 'Bulwark Gyro', 'Purge Gyro', 'Shredder Gyro', 'Spectrum Shield', 'Hard Light Arena', 'Laser Disk', 'Photon Wall', 'Barrier Signet', 'Force Signet', 'Shift Signet', 'Superconducting Signet']
elite = ['Elite Mortar Kit', 'Elixir X', 'Supply Crate', 'Sneak Gyro', 'Prime Light Beam', 'Overclock Signet']
[professions.weapons]
[professions.weapons.base]
main_hand = ['pistol']
off_hand = ['pistol', 'shield']
two_hand = ['rifle']
[professions.weapons.heart_of_thorns]
two_hand = ['hammer']
[professions.weapons.path_of_fire]
main_hand = ['sword']
[professions.weapons.end_of_dragons]
main_hand = ['mace']
[professions.weapons.secrets_of_the_obscure]
two_hand = ['shortbow']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'elementalist'
specializations = ['Fire', 'Air', 'Earth', 'Water', 'Arcane', 'Tempest', 'Weaver', 'Catalyst']
[professions.skills]
heal = ['Arcane Brilliance', 'Ether Renewal', 'Glyph of Elemental Harmony', 'Signet of Restoration', 'Wash the Pain Away!', 'Aquatic Stance', 'Soothing Water']
utility = ['Arcane Blast', 'Arcane Power', 'Arcane Shield', 'Arcane Wave', 'Armor of Earth', 'Cleansing Fire', 'Lightning Flash', 'Mist Form', 'Conjure Earth Shield', 'Conjure Flame Axe', 'Conjure Frost Bow', 'Conjure Lightning Hammer', 'Glyph of Elemental Power', 'Glyph of Lesser Elementals', 'Glyph of Renewal', 'Glyph of Storms', 'Signet of Air', 'Signet of Earth', 'Signet of Fire', 'Signet of Water', 'Feel the Burn!', 'Eye of the Storm!', 'Aftershock!', 'Flash-Freeze!', 'Primordial Stance', 'Stone Resonance', 'Unravel', 'Twist of Fate', 'Fortified Earth', 'Relentless Fire', 'Invigorating Air', 'Shattering Ice']
elite = ['Conjure Fiery Greatsword', 'Glyph of Elementals', 'Tornado', 'Rebound!', 'Weave Self', 'Elemental Celerity']
[professions.weapons]
[professions.weapons.base]
main_hand = ['dagger', 'scepter']
off_hand = ['dagger', 'focus']
two_hand = ['staff']
[professions.weapons.heart_of_thorns]
off_hand = ['warhorn']
[professions.weapons.path_of_fire]
main_hand = ['sword']
[professions.weapons.end_of_dragons]
two_hand = ['hammer']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['pistol']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'mesmer'
specializations = ['Domination', 'Dueling', 'Chaos', 'Inspiration', 'Illusions', 'Chronomancer', 'Mirage', 'Virtuoso']
[professions.skills]
heal = ['Ether Feast', 'Mirror', 'Mantra of Recovery', 'Signet of the Ether', 'Well of Eternity', 'False Oasis', 'Twin Blade Restoration']
utility = ['Decoy', 'Mirror Image', 'Feedback', 'Nullfield', 'Portal Entre', 'Veil', 'Arcane Thievery', 'Blink', 'Illusion of Life', 'Mimic', 'Mantra of Concentration', 'Mantra of distraction', 'Mantra of Pain', 'Mantra of Resolve', 'Phantasmal Defender', 'Phantasmal Disenchanter', 'Signet of Domination', 'Signet of Illusions', 'Signet of Inspiration', 'Signet of Midnight', 'Well of Action', 'Well of Calamity', 'Well of Precognition', 'Well of Recall', 'Crystal Sands', 'Illusionary Ambush', 'Mirage Advance', 'Sand Through Glass', 'Blade Renewal', 'Psychic Force', 'Rain of Swords', 'Sword of Decimation']
elite = ['Time Warp', 'Mass Invisibility', 'Signet of Humility', 'Gravity Well', 'Jaunt', 'Thousand Cuts']
[professions.weapons]
[professions.weapons.base]
main_hand = ['sword', 'scepter']
off_hand = ['pistol', 'sword', 'focus', 'torch']
two_hand = ['greatsword', 'staff']
[professions.weapons.heart_of_thorns]
off_hand = ['shield']
[professions.weapons.path_of_fire]
main_hand = ['axe']
[professions.weapons.end_of_dragons]
main_hand = ['dagger']
[professions.weapons.secrets_of_the_obscure]
two_hand = ['rifle']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
[[professions]]
name = 'necromancer'
specializations = ['Spite', 'Curses', 'Death Magic', 'Blood Magic', 'Soul Reaping', 'Reaper', 'Scourge', 'Harbinger']
[professions.skills]
heal = ['Consume Conditions', 'Summon Blood Fiend', 'Signet of Vamparism', 'Well of Blood', 'Your Soul is Mine!', 'Sand Flare', 'Elixir of Promise']
utility = ['Blood is Power', 'Corrosive Poison Cloud', 'Corrupt Boon', 'Epidemic', 'Summon Bone Fiend', 'Summon Bone Minion', 'Summon Flesh Worm', 'Summon Shadow Fiend', 'Plague Signet', 'Signet of Spite', 'Signet of the Locust', 'Signet of Undeath', 'Spectral Armor', 'Spectral Grasp', 'Spectral Walk', 'Spectral Ring', 'Well of Corruption', 'Well of Darkness', 'Well of Power', 'Well of Suffering', 'Nothing can save you!', 'Rise!', 'Suffer!', 'You are all Weaklings!', 'Trail of Anguish', 'Dessicate', 'Sand Swell', 'Serpent Siphon', 'Elixir of Anguish', 'Elixir of Bliss', 'Elixir of Ignorance', 'Elixir of Risk']
elite = ['Plaguelands', 'Summon Flesh Golem', 'Lich Form', 'Chill to the Bone!', 'Ghastly Breach', 'Elixir of Ambition']
[professions.weapons]
[professions.weapons.base]
main_hand = ['axe', 'dagger', 'scepter']
off_hand = ['dagger', 'focus', 'warhorn']
two_hand = ['staff']
[professions.weapons.heart_of_thorns]
two_hand = ['greatsword']
[professions.weapons.path_of_fire]
off_hand = ['torch']
[professions.weapons.end_of_dragons]
main_hand = ['pistol']
[professions.weapons.secrets_of_the_obscure]
main_hand = ['sword']
off_hand = ['sword']
[professions.weapons.janthir_wilds]
two_hand = ['spear']
