# You can customise the include/exclude list for classes here

include_professions = [
    "warrior",
    "guardian",
    "revenant",
    "ranger",
    "thief",
    "engineer",
    "elementalist",
    "mesmer",
    "necromancer",
]
exclude_professions = []
