# You can customise the include/exclude list for classes here

include_classes = [
    "WARRIOR",
    "GUARDIAN",
    "REVENANT",
    "RANGER",
    "THIEF",
    "ENGINEER",
    "ELEMENTALIST",
    "MESMER",
    "NECROMANCER",
]
exclude_classes = []
